# =====================================================================
# HYPRLAND MAIN CONFIG — hyprland.conf
# Edit variables here. Everything else lives in the sourced files.
# Hyprland 0.54
# =====================================================================

# -------------------------
# MODIFIER KEY
# -------------------------
$mainMod = SUPER

# -------------------------
# APPLICATIONS
# Change these to your preferred apps
# -------------------------
$h = ~/.config/hypr

$terminal    = foot
$browser     = brave
$fileManager = thunar
$scripts     = ~/scripts
$hscripts    = $h/scripts 
# -------------------------
# MONITOR
# See https://wiki.hypr.land/Configuring/Monitors/
# Format: monitor = <name>, <resolution>@<hz>, <position>, <scale>
# Use `hyprctl monitors` to list connected displays
# -------------------------
monitor = , 1920x1080@60, 0x0, 1


# -------------------------
# ENVIRONMENT VARIABLES
# -------------------------
env = GTK_THEME, Adwaita:dark
env = XCURSOR_SIZE, 24
env = HYPRCURSOR_SIZE, 24
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland

# -------------------------
# PERMISSIONS
# See https://wiki.hypr.land/Configuring/Permissions/
# Changes here require a Hyprland restart
# -------------------------
permission = /usr/(bin|local/bin)/grim, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

# -------------------------
# INCLUDES
# -------------------------
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/general.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/noctalia.conf
