package.path = os.getenv("HOME") .. "/.config/hypr/modules/?.lua;" .. package.path

require("settings")
hlc = require("hlc")
hlc.notify("Hyprland Config Reloaded")

require("keybindings")

-- require("test")
require("monitors")
require("environment")
require("appearance")
require("input")
require("rules")

-- hlc.notify("Tesitng testing testing\n testing", { icon = "error", color = "0xff00ffff" })
hlc.config.autogenerated = false

hl.config({
    plugin = {
        csgo_vulkan_fix = {
            fix_mouse = true,
        },
    },
})

hl.plugin.csgo_vulkan_fix.vkfix_app({ app = "cs2", w = 1440, h = 1080 })


