package.path = os.getenv("HOME") .. "/.config/hypr/modules/?.lua;" .. package.path

local s = require("settings")
local hlc = require("hlc")
hlc.notify("Hyprland Config Reloaded")

require("keybindings")

require("test")
-- require("example")
require("monitors")
require("environment")
require("appearance")
require("input")
require("rules")

-- hlc.notify("Tesitng testing testing\n testing", { icon = "error", color = "0xff00ffff" })
hlc.config.autogenerated = false


