
$ipc = qs -c noctalia-shell ipc call
exec-once = qs -c noctalia-shell

bind = ,XF86Launch1  , exec, $ipc settings open
bind = $mainMod,f1 , exec, $ipc settings open


bind = $mainMod SHIFT, U, exec, pkill qs; qs -c noctalia-shell
