# Shell
shell fish

# Font
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        12.0

# Padding
window_padding_width 10

# Opacity
background_opacity 0.5

# Scrollback
scrollback_lines 10000

# Cursor
cursor_shape           beam
cursor_beam_thickness  1.5
cursor_blink_interval  0.5

# Colors (Catppuccin Mocha — from noctalia theme, bg overridden to 101010)
foreground            #e7e1e5
background            #101010
selection_foreground  #4c2529
selection_background  #f4b7bb

# Black
color0  #45475a
color8  #585b70
# Red
color1  #f38ba8
color9  #f37799
# Green
color2  #a6e3a1
color10 #89d88b
# Yellow
color3  #f9e2af
color11 #ebd391
# Blue
color4  #89b4fa
color12 #74a8fc
# Magenta
color5  #f5c2e7
color13 #f2aede
# Cyan
color6  #94e2d5
color14 #6bd7ca
# White
color7  #a6adc8
color15 #bac2de

# Tab bar
tab_bar_edge        bottom
tab_bar_style       powerline
tab_powerline_style slanted
tab_title_template  {index}: {title}

# Tab switching (Alt+1–9)
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

# Tab management
map alt+t new_tab
map alt+w close_tab
map alt+, previous_tab
map alt+. next_tab
